on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing covid-19 and its dependencies
        run: raco pkg install --no-docs --auto --name covid-19
      - name: Compiling covid-19 and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps covid-19
      - name: Testing covid-19
        run: raco test -x -p covid-19

      - name: build docs for GP
        run: |
          raco scribble \
          --dest doc \
          --dest-name index \
          ++main-xref-in \
          --redirect-main https://docs.racket-lang.org/ \
          --redirect https://docs.racket-lang.org/local-redirect/index.html \
          scribblings/covid-19.scrbl
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          target_branch: gh-pages
          build_dir: doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
